BugTracking/Controllers/AuthenticateController.cs
using BugTracking.DAO;
using BugTracking.Models;
using BugTracking.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BugTracking.Controllers
{
    public class AuthenticateController : Controller
    {
        // GET: /<controller>/
        ApplicationDbContext _context;
        public AuthenticateController(ApplicationDbContext context)
        {
            _context = context;
        }


        public IActionResult Login()
        {
            HttpContext.Session.Remove("USER_INFO");
            return View();
        }

        [HttpPost]
        public JsonResult SignIn([FromBody] LoginVM vm)
        {
            Users usr = _context.Users
                 .Where(x => x.Status == 1
                  && x.Username == vm.Username
                  && x.Password == vm.Password
                 )
                 .FirstOrDefault();
            if (usr == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "User Not Found"
                });
            }
            else
            {
                HttpContext.Session.SetString("USER_INFO", usr.UsersID.ToString());

                return Json(new
                {
                    Success = true,
                });
            }
        }
    }
}

BugTracking/Controllers/UserGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracking.DAO;
using BugTracking.Models;
using BugTracking.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BugTracking.Controllers
{
    public class UserGroupController : BaseController
    {

        ApplicationDbContext _context;
        public UserGroupController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Create([FromBody] UserGroup ui)
        {
            if (string.IsNullOrEmpty(ui.UserGroupName))
            {
                return Json(new
                {
                    Success = false,
                    Message = "Enter User Group Name..."
                });

            }
            else if (string.IsNullOrEmpty(ui.UserGroupCode))
            {
                return Json(new
                {
                    Success = false,
                    Message = "Enter User Group Code..."
                });
            }
            else
            {
                if (ui.UserGroupID == 0)
                {
                    //add part i.e. create new user group
                    UserGroup oldCode = _context.UserGroup
                         .Where(x => x.UserGroupCode == ui.UserGroupCode)
                         .FirstOrDefault();

                    if (oldCode == null)
                    {
                        UserGroup ug = new UserGroup()
                        {
                            UserGroupName = ui.UserGroupName,
                            UserGroupCode = ui.UserGroupCode,
                            Status = 1,
                            ActivateDate = DateTime.Now
                        };

                        _context.UserGroup.Add(ug);
                        _context.SaveChanges();

                        return Json(new
                        {
                            Success = true,
                            Message = "User Group Added Successfully..."
                        });
                    }
                    else
                    {
                        return Json(new
                        {
                            Success = false,
                            Message = "User Group Code Already Exist..."
                        });
                    }
                }
                else
                {
                    // update part
                    UserGroup oldGrp = _context.UserGroup.Where(x => x.UserGroupID == ui.UserGroupID).FirstOrDefault();
                    if (oldGrp == null)
                    {
                        return Json(new
                        {
                            Success = false,
                            Message = "User Group Information Not Found..."
                        });
                    }
                    else
                    {
                        oldGrp.UserGroupName = ui.UserGroupName;
                        oldGrp.UserGroupCode = ui.UserGroupCode;

                        _context.SaveChanges();

                        return Json(new
                        {
                            Success = true,
                            Message = "User Group Information Updated Successfully..."
                        });
                    }
                }
            }
        }

        [HttpGet]
        public JsonResult Delete(int id)
        {
            UserGroup oldGroup = _context.UserGroup.Where(x => x.UserGroupID == id).FirstOrDefault();
            if (oldGroup == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "User Group Information Not Found..."
                });
            }
            else
            {
                oldGroup.Status = 0;
                _context.SaveChanges();


                return Json(new
                {
                    Success = true,
                    Message = "User Group Information Deleted Successfully..."
                });
            }
        }

        [HttpGet]
        public JsonResult GetAllData(string grpname, string grpcode)
        {
            List<UserGroupVM> ugs = _context
                .UserGroup
                .Where(x => x.Status == 1
                   && (string.IsNullOrEmpty(grpname) || x.UserGroupName.Contains(grpname))  // grpname = admin
                   && (string.IsNullOrEmpty(grpcode) || x.UserGroupCode.Contains(grpcode))  // grpname = admin
                )
                .Select(s => new UserGroupVM
                {
                    UserGroupID = s.UserGroupID,
                    UserGroupName = s.UserGroupName,
                    UserGroupCode = s.UserGroupCode,
                    ActivateDate = s.ActivateDate.Value.ToString("yyyy/MM/dd")
                })
                .ToList();

            return Json(new
            {
                Success = true,
                Data = ugs
            });
        }

        [HttpGet]
        public JsonResult GetByID(int id)
        {
            UserGroup ug = _context.UserGroup.Where(x => x.UserGroupID == id).FirstOrDefault();
            if (ug == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "User Group Information Not Found..."
                });
            }
            else
            {
                return Json(new
                {
                    Success = true,
                    Data = ug
                });
            }
        }

    }
}

BugTracking/Views/Authenticate/Temp.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Signin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sign-in/">-->

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="~/css/signin.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="text-center">
    <form class="form-signin">
        <img class="mb-4" src="https://broadwayinfosys.com/uploads/logo/1705900306_15549.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label class="sr-only">UserName </label>
        <input type="text" id="txtUsername" class="form-control mb-2" autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="txtPassword" class="form-control">
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block btnSignIn" type="button">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2024-2025</p>
    </form>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $(document).on('click', '.btnSignIn', function () {
            var username = $('#txtUsername').val() || '';
            var password = $('#txtPassword').val() || '';

            if (username == '') {
                alert('Enter Username')
            } else if (password == '') {
                alert('Enter Password')
            } else {
                // Optionally save username and password to localStorage if "Remember me" is checked
                if ($('input[type="checkbox"]').is(':checked')) {
                    localStorage.setItem('USERNAME', username);
                    localStorage.setItem('PASSWORD', password);
                }
                var obj = {
                    Username: username,
                    Password: password
                }
                $.ajax({
                    method: 'post',
                    contentType: "application/json; charset=utf-8",
                    url: '@Url.Action("SignIn","Authenticate")',
                    data: JSON.stringify(obj),
                    success: function (res) {
                        if (res.success) {
                            window.location.href = "@Url.Action("Index","UserGroup")";
                        } else {
                           alert(res.message)
                        }
                    },
                    error: function (e) { },
                    beforeSend: function () {
                        //block ui
                        //$.blockUI();
                    },
                    complete: function () {
                        // unblock ui
                        //$.unBlockUI();
                    }
                })
            }
        });
        window.onload = function () {
            var storedUsername = localStorage.getItem('USERNAME');
            var storedPassword = localStorage.getItem('PASSWORD');

            if (storedUsername) {
                $('#txtUsername').val(storedUsername);
            }
            if (storedPassword) {
                $('#txtPassword').val(storedPassword);
            }

        };
    </script>

    <script>toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }</script>
</body>
</html>