BugTracking/Controllers/ComplainFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracking.DAO;
using BugTracking.Models;
using BugTracking.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BugTracking.Controllers
{
    public class ComplainFormController : Controller
    {
        ApplicationDbContext _context;
        public ComplainFormController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Form()
        {
            return View();
        }
        public IActionResult track()
        {


            return View();

        }
        [HttpGet]
        public JsonResult GetAllData(string CUSTOMERNO)
        {
            List<ComplainVM> u = _context
                            .Complain
                            .Where(x => (string.IsNullOrEmpty(CUSTOMERNO) || x.CustomerNo == CUSTOMERNO))

                            .Select(s => new ComplainVM
                            {
                                ComplainInfoID = s.ComplainInfoID,
                                ComplainNo = s.ComplainNo,
                                Fullname = s.Fullname,
                                Address = s.Address,
                                ContactNo = s.ContactNo,
                                Email = s.Email,
                                Statement = s.Statement,
                                IssueDate = s.IssueDate,
                                CreatedDate = s.CreatedDate,

                            })
                            .ToList();

            return Json(new
            {
                Success = true,
                Data = u
            });
        }
        [HttpGet]
        public JsonResult Create(string CUSTOMERID, string FULLNAME, string ADDRESS, string CONTACTNO, string EMAIL, string STATEMENT, string ISSUEDATE)
        {
            if (string.IsNullOrEmpty(CUSTOMERID))
            {

                return Json(new
                {
                    sucess = false,
                    Message = "Enter Your Customer ID!.."
                });
            }
            else if (string.IsNullOrEmpty(FULLNAME))
            {

                return Json(new
                {
                    sucess = false,
                    Message = "Enter Your FullName!..."
                });
            }
            else if (string.IsNullOrEmpty(ADDRESS))
            {

                return Json(new
                {
                    sucess = false,
                    Message = "Enter Your Address!..."
                });
            }
            else if (string.IsNullOrEmpty(CONTACTNO))
            {

                return Json(new
                {
                    sucess = false,
                    Message = "Enter Your Contact Number!..."
                });
            }
            else if (string.IsNullOrEmpty(EMAIL))
            {

                return Json(new
                {
                    sucess = false,
                    Message = "Enter Your Email Address!..."
                });
            }
            else if (string.IsNullOrEmpty(STATEMENT))
            {

                return Json(new
                {
                    sucess = false,
                    Message = "Enter Your Issue!..."
                });
            }
            else if (string.IsNullOrEmpty(ISSUEDATE))
            {

                return Json(new
                {
                    sucess = false,
                    Message = "Enter Your Issue Occur Date!..."
                });
            }
            else
            {
                string cmp = "CMP-" + (_context.Complain.Count() + 1).ToString();
                Complain c = new Complain
                {
                    ComplainNo = cmp,
                    CustomerNo = CUSTOMERID,
                    Fullname = FULLNAME,
                    Address = ADDRESS,
                    Email = EMAIL,
                    ContactNo = CONTACTNO,
                    Statement = STATEMENT,
                    IssueDate = DateTime.Parse(ISSUEDATE),
                    CreatedDate = DateTime.Now
                };

                _context.Complain.Add(c);
                _context.SaveChanges();


                ComplainStatusTrackInfo ti = new ComplainStatusTrackInfo()
                {
                    ComplainInfoID = c.ComplainInfoID,
                    TargetStatusID = 1,
                    Remarks = "",
                    CreatedBy = 0,
                    CreatedDate = DateTime.Now
                };

                _context.ComplainStatusTrackInfo.Add(ti);
                _context.SaveChanges();


                return Json(new
                {
                    Success = true,
                    Message = "Complain Submitted Successfully... Your Complain No is: " + c.ComplainNo
                });
            }

        }

        [HttpGet]
        public JsonResult GetByComplainNo(string no, int id)
        {
            ComplainVM complain = _context.Complain
                .Where(x =>
                       (string.IsNullOrEmpty(no) || x.ComplainNo == no)
                       && (id == 0 || x.ComplainInfoID == id)
                )
                .Select(s => new ComplainVM
                {
                    Address = s.Address,
                    ComplainInfoID = s.ComplainInfoID,
                    ComplainNo = s.ComplainNo,
                    ContactNo = s.ContactNo,
                    CreatedDate = s.CreatedDate,
                    CustomerNo = s.CustomerNo,
                    Email = s.Email,
                    Fullname = s.Fullname,
                    IssueDate = s.IssueDate,
                    Statement = s.Statement,
                })
                .FirstOrDefault();


            if (complain == null)
            {
                return Json(new
                {
                    success = false,
                    Message = "Complain Info Not Found..."
                });
            }
            else
            {
                complain.TrackInfos = _context.ComplainStatusTrackInfo
                .Where(x => x.ComplainInfoID == complain.ComplainInfoID)
                .Select(s => new ComplainStatusTrackInfoVM
                {
                    ComplainInfoID = s.ComplainInfoID,
                    ComplainStatusTrackInfoID = s.ComplainStatusTrackInfoID,
                    CreatedBy = s.CreatedBy,
                    CreatedDate = s.CreatedDate,
                    Remarks = s.Remarks.ToString(),
                    TargetStatusID = s.TargetStatusID,
                    TargetStatusName = s.ComplainStatus.StatusName,
                    TargetStatusCode = s.ComplainStatus.StatusCode
                })
                .ToList();

                return Json(new
                {
                    success = true,
                    Message = "Complain Info Found...",
                    Data = complain
                });
            }
        }
    }
}

BugTracking/Controllers/ComplainStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracking.DAO;
using BugTracking.Models;
using BugTracking.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BugTracking.Controllers
{
    public class ComplainStatusController : Controller
    {
        ApplicationDbContext _context;
        public ComplainStatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        public JsonResult GetAllComplainStatus()
        {
            var data = _context.ComplainStatus.Where(x => x.IsActive == true)
                 .Select(s => new
                 {
                     ComplainStausID = s.ComplainStatusID,
                     StatusName = s.StatusName
                 })
                 .ToList();

            return Json(new
            {
                Success = true,
                Data = data
            });
        }


        [HttpPost]
        public JsonResult Create([FromBody] ComplainStatusTrackInfoVM model)
        {
            ComplainStatusTrackInfo obj = new ComplainStatusTrackInfo();

            obj.ComplainInfoID = model.ComplainInfoID;
            obj.TargetStatusID = model.TargetStatusID;
            obj.Remarks = model.Remarks;
            obj.CreatedBy = 1;
            obj.CreatedDate = DateTime.Now;

            _context.ComplainStatusTrackInfo.Add(obj);
            _context.SaveChanges();


            return Json(new
            {
                Success = true,
                Message = "Complain Status Tracked Successfully..."
            });
        }
    }
}

BugTracking/Views/ComplainForm/Track.cshtml
@using BugTracking.Models.ViewModel;

<h4>Tracking </h4>
<div class='row'>
    <div class='col-md-12 mb-2'>
        <div class='card'>
            <div class='card-body'>
                <div class='row'>
                    <div class="col-md-3 ">
                        <label>CustumerNo</label><br />
                        <input tpye="text" class=" form-control txtSCustomerNo " />
                    </div>
                    <div class="col-md-3 ">
                        <br />
                        <button type="button" class=" btn btn-success btn-md btnSearch">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body" style="overflow:auto">
                <table class="table table-hover dtTable ">
                    <thead>
                        <tr>
                            <th>SN</th>
                            <th>ComplainInfoID</th>
                            <th>ComplainNo</th>
                            <th>Fullname</th>
                            <th>Email</th>
                            <th>ContactNo</th>
                            <th>Statement</th>
                            <th>Address</th>
                            <th>IssueDate</th>
                            <th>CreatedDate</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody class="data-list">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="mdlComplainDetail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Complain Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-body">

                                <div class="row">
                                    <div class="col-md-6">
                                        <label><u>Complain No</u></label><br />
                                        <label class="lblComplainNo"></label>
                                    </div>
                                    <div class="col-md-6">
                                        <label><u>Fullname</u></label><br />
                                        <label class="lblFullname"></label>
                                    </div>
                                    <div class="col-md-6">
                                        <label><u>Email</u></label><br />
                                        <label class="lblEmail"></label>
                                    </div>
                                    <div class="col-md-6">
                                        <label><u>Statement</u></label><br />
                                        <label class="lblStatement"></label>
                                    </div>
                                </div>

                                <div class="row mt-2" style="overflow:auto;">
                                    <h4>Track Info</h4>
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>Status Name</th>
                                                <th>Remarks</th>
                                                <th>Date</th>
                                            </tr>
                                        </thead>
                                        <tbody class="bodyTrackInfo"></tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <label>Targe Status</label><br />
                                <select class="form-control ddlComplainStatus">
                                </select> <br />

                                <label>Remarks</label><br />
                                <input type="text" class="form-control txtRemarks" />

                                <div class="card-footer">
                                    <input type="hidden" value="0" class="hdnComplainID" />
                                    <button type="button" class="btn btn-primary btnSubmit"><i class="fa fa-save"></i> Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
 </div>
@section Scripts {


    <script>
        $(document).ready(function () {
            loadData();
            loadComplainStatus();
        })

        function loadComplainStatus(){
            $.ajax({
                method:'get',
                contentType:"application/json: charset=utf-8",
                 url: '@Url.Action("GetAllComplainStatus", "ComplainStatus")',
                 success: function(res){
                     if(res.success){
                         var statusList = res.data;
                         var htmls = '<option value="0">--select--</option>';
                         $.each(statusList, function (i, x) {
                             htmls += "<option value='" + x.complainStausID + "'>" + x.statusName + "</option>";
                         })

                         $('.ddlComplainStatus').html(htmls)
                     }else{

                     }
                 },
                 error:function(e){},
                 beforesend:function(){
                     //
                 },
                 complete: function(){
                     //$.unblockui();
                 }
            });
        }

        $(document).on('click', '.btnSearch', function () {
            loadData();
        });
        function loadData() {
            var Customerno = $('.txtSCustomerNo').val() || '';
            $.ajax({
                method: 'get',
                contentType:"application/json: charset=utf-8",
                url: '@Url.Action("GetAllData", "ComplainForm")?CUSTOMERNO=' + Customerno,
                success: function (res) {
                    if (res.success) {
                        var allData = res.data;
                        var htmlString = "";
                        $.each(allData, function (i, x) {
                            htmlString += "<tr>";
                            htmlString += "<td>" +(i+1) + "</td>";
                            htmlString += "<td>"+  x.complainInfoID+ "</td>";
                            htmlString += "<td>"+ x.complainNo + "</td>";
                            htmlString += "<td>" +x.fullname + "</td>";
                            htmlString += "<td>"+  x.email + "</td>";
                            htmlString += "<td>"+ x.contactNo+ "</td>";
                            htmlString += "<td>"+ x.statement + "</td>";
                            htmlString += "<td>" +x.address + "</td>";
                            htmlString += "<td>"+  x.issueDate+ "</td>";
                            htmlString += "<td>"+ x.createdDate+ "</td>";
                            htmlString +="<td>";
                            htmlString += "<button type= 'button' class='btn btn-secondary btnEdit btn-sm' data-key='" +x.complainInfoID + "'>Edit</button>";
                            htmlString +=" <button type= 'button' class='btn btn-success btnTrack btn-sm' data-key='" +x.complainInfoID +"'>Track</button>";
                            htmlString +="</td>";
                            htmlString += "</tr>";
                        });
                        $('.data-list').html(htmlString);
                        $('.dtTable').DataTable();
                    } else {
                    }
                },
                error: function (e) { },
                beforesend: function () {
                    //
                },
                complete: function () {
                    //$.unblockui();
                }
            });
            }
    </script>

    <script>
        $(document).on('click', '.btnTrack', function () {
            var complainId = $(this).data('key');
            $.ajax({
                    method: 'get',
                    contentType: "application/json; charset=utf-8",
                    url: '@Url.Action("GetByComplainNo", "ComplainForm")?id=' + complainId,
                    success: function (res) {
                        if (res.success) {

                            $('#mdlComplainDetail').modal('show');

                            $('.lblComplainNo').html(res.data.complainNo);
                            $('.lblFullname').html(res.data.fullname);
                            $('.lblEmail').html(res.data.email);
                            $('.lblStatement').html(res.data.statement);
                            $('.hdnComplainID').val(res.data.complainInfoID);

                            var trackInfo = res.data.trackInfos;

                            var htmls = '';
                            $.each(trackInfo, function (i, x) {
                                htmls += "<tr>";
                                htmls += "<td>" + x.targetStatusName + "</td>";
                                htmls += "<td>" + x.remarks + "</td>";
                                htmls += "<td>" + x.createdDate + "</td>";
                                htmls += "</tr>";
                            });

                            $('.bodyTrackInfo').html(htmls);

                        } else {
                            Swal.fire({
                                title: "error",
                                text: res.message,
                                icon: "error"
                            });
                        }
                    },
                    error: function (e) { },
                    beforeSend: function () {

                        //$.blockUI();
                    },
                    complete: function () {

                        //   $.unblockUI();
                    }
                });
        });
        $(document).on('click', '.btnSubmit', function () {
            var targetStatusID = $('.ddlComplainStatus').val() || 0;
            var remarks = $('.txtRemarks').val() || '';

            if (targetStatusID == 0) {
                alert('Select Target Status')
            } else if (!remarks) {
                alert('Enter Remarks')
            } else {

                var obj = {
                    targetStatusID: +targetStatusID,
                    remarks: remarks,
                    complainInfoID: +$('.hdnComplainID').val()
                };
                $.ajax({
                    method: 'post',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(obj),
                    url: '@Url.Action("Create", "ComplainStatus")',
                   success: function (res) {
                        if (res.success) {
                            Swal.fire({
                                title: "success",
                                text: res.message,
                                icon: "success"
                            });
                            $('#mdlComplainDetail').modal('hide');

                        } else {
                            Swal.fire({
                                title: "error",
                                text: res.message,
                                icon: "error"
                            });
                        }
                    },
                   error: function (e) { },
                   beforeSend: function () {

                        //$.blockUI();
                   },
                   complete: function () {

                        //   $.unblockUI();
                   }
                });
            }

        })
    </script>
}